### ISSUE TITLE
Not working with 2.2.3

### ISSUE THREAD

**Issue by vnikolaenko** [gatling-cql/GatlingCql#12]
```
Exception in thread "main" java.lang.NoSuchMethodError: io.gatling.core.protocol.ProtocolComponentsRegistry.protocols()Lio/gatling/core/protocol/Protocols;
	at io.github.gatling.cql.request.CqlRequestActionBuilder.build(CqlRequestActionBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder$class.io$gatling$core$structure$StructureBuilder$class$$$anonfun$1(StructureBuilder.scala:34)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at io.gatling.core.structure.StructureBuilder$class.build(StructureBuilder.scala:33)
	at io.gatling.core.structure.ChainBuilder.build(ChainBuilder.scala:30)
	at io.gatling.core.action.builder.LoopBuilder.build(LoopBuilder.scala:44)
	at io.gatling.core.structure.StructureBuilder$class.io$gatling$core$structure$StructureBuilder$class$$$anonfun$1(StructureBuilder.scala:34)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at io.gatling.core.structure.StructureBuilder$class.build(StructureBuilder.scala:33)
	at io.gatling.core.structure.ScenarioBuilder.build(ScenarioBuilder.scala:38)
	at io.gatling.core.structure.PopulationBuilder.build(ScenarioBuilder.scala:98)
	at io.gatling.core.scenario.SimulationParams.io$gatling$core$scenario$SimulationParams$$$anonfun$15(Simulation.scala:188)
	at scala.collection.immutable.List.map(List.scala:273)
	at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:188)
	at io.gatling.app.Runner.run0(Runner.scala:95)
	at io.gatling.app.Runner.run(Runner.scala:64)
	at io.gatling.app.Gatling$.start(Gatling.scala:56)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:41)
	at io.gatling.app.Gatling$.main(Gatling.scala:33)
	at io.gatling.app.Gatling.main(Gatling.scala)

```

**Comment by Mishail** [comment]
@vnikolaenko please check how v0.0.6 works for you.
